/// <reference types="cypress" />
import messages from '@/i18n/messages'

describe('English tests', {
  env: {
    discordURL: 'https://discord.gg/RTXr8A3eFn',
    facebookURL: 'https://www.facebook.com/schrodingerhat',
    githubURL: 'https://github.com/Schrodinger-Hat',
    githubWebsiteRepoURL: 'https://github.com/Schrodinger-Hat/schrodinger-hat-website/issues/new/choose',
    imageGoNordURL: 'https://ign.schrodinger-hat.it',
    instagramURL: 'https://www.instagram.com/schrodinger_hat/',
    linkedinURL: 'https://www.linkedin.com/company/schrodinger-hat/',
    // Modify with your local environment url
    localhost: 'http://localhost:5173',
    openCollectiveURL: 'https://opencollective.com/schrodinger-hat',
    spotifyURL: 'https://open.spotify.com/show/7yfkQCV6hrPIqflSqJDB2P',
    twitterURL: 'https://twitter.com/schrodinger_hat',
    youtubeURL: 'https://www.youtube.com/channel/UC1QLLgrGrPmlaFhS0orykCA',
  },
}, () => {
  beforeEach(() => {
    // Sets the website language website to 'en_US'
    cy.visit(Cypress.env('localhost'), {
      onBeforeLoad(win) {
        Object.defineProperty(win.navigator, 'language', {
          value: 'en_US',
        })
      },
    })
    // Wait for mailchimp modal to appear.
    // As the modal is loaded async, edit the time depending on your situation.
    cy.wait(5000).then(() => {
      cy.get('.mc-closeModal').click()
    })
  })
  describe.skip('Navbar tests', () => {
    it('Changes to mobile viewport, assures all CTAs work correctly', () => {
      cy.viewport('iphone-xr')
      cy.get('[data-test="nav-wrapper"]').should('be.visible').and('exist')
      cy.get('[data-test="nav-logo-button"]').should('be.visible').and('have.attr', 'href').and('include', '/')
      cy.get('[data-test="logo-text"]').should('be.visible').and('contain.text', 'Schrödinger Hat')
      cy.get('[data-test="nav-team-page-link"]').should('not.be.visible')
      cy.get('[data-test="nav-event-page-link"]').should('not.be.visible')
      cy.get('[data-test="nav-conduct-page-link"]').should('not.be.visible')
      cy.get('[data-test="nav-go-nord-page-link"]').should('not.be.visible')
      cy.get('[data-test="nav-github-page-link"]').should('have.attr', 'href').and('include', Cypress.env('githubURL'))
      cy.get('html').then(($html) => {
        const oldClass = $html[0].getAttribute('class')
        cy.get('[data-test="nav-theme-cta"]').click()
        cy.get('html').should('not.have.class', oldClass)
      })
      cy.get('[data-test="mobile-menu"]').should('not.exist')
      cy.get('[data-test="nav-burger-menu-cta"]').click()
      cy.get('[data-test="mobile-menu"]').should('exist')
      cy.get('[data-test="mobile-burger-menu-cta"]').should('exist').click()
      cy.get('[data-test="mobile-menu"]').should('not.exist')
      cy.get('[data-test="nav-burger-menu-cta"]').click()
      // TODO: Include GitHub and ImageGoNord into the messages
      cy.get('[data-test="mobile-github-page-link"]')
        .should('exist')
        .and('contain.text', 'GitHub')
        .and('have.attr', 'href', Cypress.env('githubURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="mobile-team-page-link"]')
        .should('exist')
        .and('contain.text', messages.en.navbar.team)
        .and('have.attr', 'href', '/team')
      cy.get('[data-test="mobile-event-page-link"]')
        .should('exist')
        .and('contain.text', messages.en.navbar.events)
        .and('have.attr', 'href', '/events')
      cy.get('[data-test="mobile-conduct-page-link"]')
        .should('exist')
        .and('contain.text', messages.en.navbar.codeOfConduct)
        .and('have.attr', 'href', '/code-of-conduct')
      cy.get('[data-test="mobile-go-nord-page-link"]')
        .should('exist')
        .and('contain.text', 'ImageGoNord')
        .and('have.attr', 'href', Cypress.env('imageGoNordURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="mobile-homepage-link"]').should('exist')
        .and('have.attr', 'href', '/').click()
      cy.get('[data-test="mobile-menu"]').should('not.exist')
      cy.url().then((url) => {
        expect(url).to.contain(Cypress.env('localhost'))
      })
    })
    it('Changes to desktop viewport, assures all CTAs work correctly', () => {
      cy.viewport('macbook-16')
      cy.get('[data-test="nav-wrapper"]').should('be.visible').and('exist')
      cy.get('[data-test="nav-logo-button"]').should('be.visible').and('have.attr', 'href').and('include', '/')
      cy.get('[data-test="logo-text"]').should('be.visible').and('contain.text', 'Schrödinger Hat')
      cy.get('[data-test="nav-wrapper"]').should('be.visible').and('exist')
      cy.get('[data-test="nav-team-page-link"]')
        .should('exist')
        .and('contain.text', messages.en.navbar.team)
        .and('have.attr', 'href', '/team')
      cy.get('[data-test="nav-event-page-link"]')
        .should('exist')
        .and('contain.text', messages.en.navbar.events)
        .and('have.attr', 'href', '/events')
      cy.get('[data-test="nav-conduct-page-link"]')
        .should('exist')
        .and('contain.text', messages.en.navbar.codeOfConduct)
        .and('have.attr', 'href', '/code-of-conduct')
      cy.get('[data-test="nav-go-nord-page-link"]')
        .should('exist')
        .and('contain.text', 'ImageGoNord')
        .and('have.attr', 'href', Cypress.env('imageGoNordURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="nav-github-page-link"]')
        .should('exist')
        .and('have.attr', 'href', Cypress.env('githubURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="nav-github-icon"]').should('have.class', 'fab fa-github').and('be.visible').and('exist')
      cy.get('html').then(($html) => {
        const oldClass = $html[0].getAttribute('class')
        cy.get('[data-test="nav-theme-cta"]').click()
        cy.get('html').should('not.have.class', oldClass)
      })
    })
  })
  describe.skip('Contributing section tests', () => {
    it('Changes to mobile viewport and assures all elements are rendered correctly', () => {
      cy.viewport('iphone-xr')
      cy.get('[data-test="contributing-section"]').should('be.visible').and('exist').scrollIntoView()
      // TODO: Rewrite test once nyan cat is disabled on mobile
      cy.get('[data-test="nyan-cat"]').then(($element) => {
        cy.wrap($element).should('not.have.class', 'loaded')
        cy.wait(300)
        cy.wrap($element).should('have.class', 'loaded')
        cy.wait(8000)
        cy.wrap($element).should('have.css', 'display', 'none')
      })
      cy.get('[data-test="contributing-title"]')
        .should('be.visible')
        .and('contain.text', messages.en.contributing.title)
      cy.get('[data-test="contributing-description"]')
        .should('be.visible')
      // TODO: Fix this way of assuring the text exists
        .and('contain.text', `Schrödinger Hat ${messages.en.contributing['is-a-project']} GitHub`)
      cy.get('[data-test="contributing-github-link"]')
        .should('be.visible')
        .and('exist')
        .and('have.attr', 'href', Cypress.env('githubURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="contributing-cta"]')
        .should('exist')
        .and('contain.text', `${messages.en.contributing.cta} ${messages.en.contributing['external-link']} ${messages.en.contributing['cta-2']}`)
      cy.get('[data-test="contributing-github-website-link"]')
        .should('be.visible')
        .and('exist')
        .and('have.attr', 'href', Cypress.env('githubWebsiteRepoURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="contributing-social"]').should('be.visible')
    })
    it('Changes to desktop viewport and assures all elements are rendered correctly', () => {
      cy.viewport('macbook-16')
      cy.get('[data-test="contributing-section"]').should('be.visible').and('exist').scrollIntoView()
      // TODO: Rewrite test once nyan cat is disabled on mobile
      cy.get('[data-test="nyan-cat"]').then(($element) => {
        cy.wrap($element).should('not.have.class', 'loaded')
        cy.wait(300)
        cy.wrap($element).should('have.class', 'loaded')
        cy.wait(8000)
        cy.wrap($element).should('have.css', 'display', 'none')
      })
      cy.get('[data-test="contributing-title"]')
        .should('be.visible')
        .and('contain.text', messages.en.contributing.title)
      cy.get('[data-test="contributing-description"]')
        .should('be.visible')
      // TODO: Fix this way of assuring the text exists
        .and('contain.text', `Schrödinger Hat ${messages.en.contributing['is-a-project']} GitHub`)
      cy.get('[data-test="contributing-github-link"]')
        .should('be.visible')
        .and('exist')
        .and('have.attr', 'href', Cypress.env('githubURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="contributing-cta"]')
        .should('exist')
        .and('contain.text', `${messages.en.contributing.cta} ${messages.en.contributing['external-link']} ${messages.en.contributing['cta-2']}`)
      cy.get('[data-test="contributing-github-website-link"]')
        .should('be.visible')
        .and('exist')
        .and('have.attr', 'href', Cypress.env('githubWebsiteRepoURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="contributing-social"]').should('be.visible')
    })
    it('Assures all social CTAs are rendered correctly', () => {
      cy.get('[data-test="contributing-social"]').should('be.visible').and('exist')
      cy.get('[data-test="contributing-open-collective"]')
        .should('exist')
        .and('have.attr', 'href', Cypress.env('openCollectiveURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="contributing-open-collective-icon"]')
        .should('be.visible')
        .and('have.class', 'fas fa-donate external-link-color')
      cy.get('[data-test="contributing-facebook"]')
        .should('exist')
        .and('have.attr', 'href', Cypress.env('facebookURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="contributing-facebook-icon"]')
        .should('be.visible')
        .and('have.class', 'fab fa-facebook external-link-color')
      cy.get('[data-test="contributing-twitter"]')
        .should('exist')
        .and('have.attr', 'href', Cypress.env('twitterURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="contributing-twitter-icon"]')
        .should('be.visible')
        .and('have.class', 'fab fa-twitter external-link-color')
      cy.get('[data-test="contributing-linkedin"]')
        .should('exist')
        .and('have.attr', 'href', Cypress.env('linkedinURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="contributing-linkedin-icon"]')
        .should('be.visible')
        .and('have.class', 'fab fa-linkedin external-link-color')
      cy.get('[data-test="contributing-instagram"]')
        .should('exist')
        .and('have.attr', 'href', Cypress.env('instagramURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="contributing-instagram-icon"]')
        .should('be.visible')
        .and('have.class', 'fab fa-instagram external-link-color')
      cy.get('[data-test="contributing-discord"]')
        .should('exist')
        .and('have.attr', 'href', Cypress.env('discordURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="contributing-discord-icon"]')
        .should('be.visible')
        .and('have.class', 'fab fa-discord external-link-color')
    })
    it('Assures all contributing partners are rendered correctly', () => {
      cy.get('[data-test="contributing-partners-logo"]').should('be.visible')
      cy.get('[data-test="contributing-partners-logo"] > a').then(($elements) => {
        cy.wrap($elements)
          .should('be.visible')
          .should('not.have.attr', 'href', '')
          .and('have.attr', 'target', '_blank')
        cy.wrap($elements.children())
          .should('be.visible')
          .and('exist')
          .and('not.have.attr', 'src', '')
          .and('not.have.attr', 'alt', '')
      })
    })
  })
  describe.skip('Footer tests', () => {
    it('Changes to mobile viewport, assures all elements are present', () => {
      cy.viewport('iphone-xr')
      cy.get('[data-test="footer"]').should('exist').and('be.visible')
      cy.get('[data-test="footer-logo"]').should('exist').and('be.visible')
      cy.get('[data-test="footer-logo"]').should('exist').and('be.visible')
      cy.get('[data-test="footer-home-link"]')
        .should('exist')
        .and('be.visible')
        .and('have.attr', 'href', '/')
      cy.get('[data-test="footer-home-link-img"]')
        .should('exist')
        .and('be.visible')
        .and('not.have.attr', 'alt', '')
      cy.get('[data-test="footer-home-link-text"]')
        .should('exist')
        .and('not.be.visible')
      cy.get('[data-test="footer-nav"]')
        .should('exist')
        .and('be.visible')
      cy.get('[data-test="footer-nav-text"]')
        .should('exist')
        .and('be.visible')
        .and('contain.text', `©${new Date().getFullYear()} Schrödinger Hat`)
    })
    it('Changes to desktop viewport, assures all elements are present', () => {
      cy.viewport('macbook-16')
      cy.get('[data-test="footer"]').should('exist').and('be.visible')
      cy.get('[data-test="footer-logo"]').should('exist').and('be.visible')
      cy.get('[data-test="footer-logo"]').should('exist').and('be.visible')
      cy.get('[data-test="footer-home-link"]')
        .should('exist')
        .and('be.visible')
        .and('have.attr', 'href', '/')
      cy.get('[data-test="footer-home-link-img"]')
        .should('exist')
        .and('be.visible')
        .and('not.have.attr', 'alt', '')
      cy.get('[data-test="footer-home-link-text"]')
        .should('exist')
        .and('be.visible')
        .and('contain.text', 'Schrödinger Hat')
      cy.get('[data-test="footer-nav"]')
        .should('exist')
        .and('be.visible')
      cy.get('[data-test="footer-nav-text"]')
        .should('exist')
        .and('be.visible')
        .and('contain.text', `©${new Date().getFullYear()} Schrödinger Hat`)
    })
  })
  describe.skip('Hero section tests', () => {
    it('Changes to mobile viewport, assures all elements are present', () => {
      cy.viewport('iphone-xr')
      cy.get('[data-test="main"]').should('be.visible').and('exist')
      cy.get('[data-test="main-h1"]').should('be.visible').and('exist').and('contain.text', messages.en.main.h1)
      cy.get('[data-test="main-h2"]').should('be.visible').and('exist').and('contain.text', messages.en.main.h2)
      cy.get('[data-test="main-cta-youtube"]')
        .should('exist')
        .and('contain.text', messages.en.main.links.youtube)
        .and('have.attr', 'href', Cypress.env('youtubeURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="main-cta-spotify"]')
        .should('exist')
        .and('contain.text', messages.en.main.links.spotify)
        .and('have.attr', 'href', Cypress.env('spotifyURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="main-cta-open-collective"]')
        .should('exist')
        .and('contain.text', messages.en.main.links.openCollective)
        .and('have.attr', 'href', Cypress.env('openCollectiveURL'))
        .and('have.attr', 'target', '_blank')
    })
    it('Changes to desktop viewport, assures all elements are present', () => {
      cy.viewport('macbook-16')
      cy.get('[data-test="main"]').should('be.visible').and('exist')
      cy.get('[data-test="main-h1"]').should('be.visible').and('exist').and('contain.text', messages.en.main.h1)
      cy.get('[data-test="main-h2"]').should('be.visible').and('exist').and('contain.text', messages.en.main.h2)
      cy.get('[data-test="main-cta-youtube"]')
        .should('exist')
        .and('contain.text', messages.en.main.links.youtube)
        .and('have.attr', 'href', Cypress.env('youtubeURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="main-cta-spotify"]')
        .should('exist')
        .and('contain.text', messages.en.main.links.spotify)
        .and('have.attr', 'href', Cypress.env('spotifyURL'))
        .and('have.attr', 'target', '_blank')
      cy.get('[data-test="main-cta-open-collective"]')
        .should('exist')
        .and('contain.text', messages.en.main.links.openCollective)
        .and('have.attr', 'href', Cypress.env('openCollectiveURL'))
        .and('have.attr', 'target', '_blank')
    })
  })
  describe.skip('Team page tests', () => {
    it('Changes the viewport to mobile, assures you can go to page from menu and assures are content is displayed correctly', () => {
      cy.viewport('iphone-xr')
      cy.get('[data-test="nav-burger-menu-cta"]').should('exist').and('be.visible').click()
      cy.get('[data-test="mobile-team-page-link"]').should('exist').and('be.visible').click()
      cy.url().should('include', `${Cypress.env('localhost')}/team`)
      cy.get('[data-test="team-list-header"]').should('be.visible').and('exist').and('contain.text', 'Schrödinger Hat\'s fam')
      cy.get('[data-test="team-card"]').then(($teamCards) => {
        const teamMessages = messages.en.team
          type TeamMemberKey = keyof typeof teamMessages
          const teamMembersQuantity = Object.keys(teamMessages).length
          const teamMembersKey = Object.keys(teamMessages)
          cy.wrap($teamCards).should('have.length', teamMembersQuantity)
          teamMembersKey.forEach((key) => {
            cy.get(`[data-test-member-name="team-member-${key}"]`).should('exist').and('be.visible')
            cy.get(`[data-test="team-member-${key}-index-photo"]`).should('exist').and('be.visible')
            cy.get(`[data-test="team-member-${key}-name"]`).should('exist').and('be.visible').and('contain.text', `${teamMessages[key as TeamMemberKey].name}`)
            if (teamMessages[key as TeamMemberKey].github_url.length > 1)
              cy.get(`[data-test="team-member-${key}-github"]`).should('have.attr', 'href', teamMessages[key as TeamMemberKey].github_url).and('have.attr', 'target', '_blank')
            if (teamMessages[key as TeamMemberKey].linkedin_url.length > 1)
              cy.get(`[data-test="team-member-${key}-linkedin"]`).should('have.attr', 'href', teamMessages[key as TeamMemberKey].linkedin_url).and('have.attr', 'target', '_blank')
            if (teamMessages[key as TeamMemberKey].twitter_url.length > 1)
              cy.get(`[data-test="team-member-${key}-twitter"]`).should('have.attr', 'href', teamMessages[key as TeamMemberKey].twitter_url).and('have.attr', 'target', '_blank')
            if (teamMessages[key as TeamMemberKey].website.length > 1)
              cy.get(`[data-test="team-member-${key}-website"]`).should('have.attr', 'href', teamMessages[key as TeamMemberKey].website).and('have.attr', 'target', '_blank')
            if (teamMessages[key as TeamMemberKey].website.length > 1)
              cy.get(`[data-test="team-member-${key}-description"]`).should('contain.text', teamMessages[key as TeamMemberKey].description)
            cy.get(`[data-test="team-member-${key}-page-link"]`).should('be.visible').and('have.attr', 'href', `/team/${key}`)
            cy.get('[data-test="team-member-redirection"]').should('be.visible').and('contain.text', messages.en.redirect.profile)
          })
      })
    })
    it('Changes the viewport to desktop, assures you can go to page from menu and assures are content is displayed correctly', () => {
      cy.viewport('macbook-16')
      cy.get('[data-test="nav-team-page-link"]').should('exist').and('be.visible').click()
      cy.url().should('include', `${Cypress.env('localhost')}/team`)
      cy.get('[data-test="team-list-header"]').should('be.visible').and('exist').and('contain.text', 'Schrödinger Hat\'s fam')
      cy.get('[data-test="team-card"]').then(($teamCards) => {
        const teamMessages = messages.en.team
          type TeamMemberKey = keyof typeof teamMessages
          const teamMembersQuantity = Object.keys(teamMessages).length
          const teamMembersKey = Object.keys(teamMessages)
          cy.wrap($teamCards).should('have.length', teamMembersQuantity)
          teamMembersKey.forEach((key) => {
            cy.get(`[data-test-member-name="team-member-${key}"]`).should('exist').and('be.visible')
            cy.get(`[data-test="team-member-${key}-index-photo"]`).should('exist').and('be.visible')
            cy.get(`[data-test="team-member-${key}-name"]`).should('exist').and('be.visible').and('contain.text', `${teamMessages[key as TeamMemberKey].name}`)
            if (teamMessages[key as TeamMemberKey].github_url.length > 1)
              cy.get(`[data-test="team-member-${key}-github"]`).should('have.attr', 'href', teamMessages[key as TeamMemberKey].github_url).and('have.attr', 'target', '_blank')
            if (teamMessages[key as TeamMemberKey].linkedin_url.length > 1)
              cy.get(`[data-test="team-member-${key}-linkedin"]`).should('have.attr', 'href', teamMessages[key as TeamMemberKey].linkedin_url).and('have.attr', 'target', '_blank')
            if (teamMessages[key as TeamMemberKey].twitter_url.length > 1)
              cy.get(`[data-test="team-member-${key}-twitter"]`).should('have.attr', 'href', teamMessages[key as TeamMemberKey].twitter_url).and('have.attr', 'target', '_blank')
            if (teamMessages[key as TeamMemberKey].website.length > 1)
              cy.get(`[data-test="team-member-${key}-website"]`).should('have.attr', 'href', teamMessages[key as TeamMemberKey].website).and('have.attr', 'target', '_blank')
            if (teamMessages[key as TeamMemberKey].website.length > 1)
              cy.get(`[data-test="team-member-${key}-description"]`).should('contain.text', teamMessages[key as TeamMemberKey].description)
            cy.get(`[data-test="team-member-${key}-page-link"]`).should('be.visible').and('have.attr', 'href', `/team/${key}`)
            cy.get('[data-test="team-member-redirection"]').should('be.visible').and('contain.text', messages.en.redirect.profile)
          })
      })
    })
  })
  describe('Team member page tests', () => {
    it('Changes to mobile viewport, assures all content is displayed correctly', () => {
      cy.viewport('iphone-xr')
      const teamMessages = messages.en.team
      type TeamMemberKey = keyof typeof teamMessages
      const memberKeys = Object.keys(teamMessages)
      memberKeys.forEach((key) => {
        cy.visit(`${Cypress.env('localhost')}/team/${key}`)
        cy.get('[data-test="member-page-photo"]').should('exist').and('be.visible')
        cy.get('[data-test="member-page-name"]').should('exist').and('be.visible').and('contain.text', `${teamMessages[key as TeamMemberKey].name}`)
        if (teamMessages[key as TeamMemberKey].github_url.length > 1)
          cy.get('[data-test="member-page-github"]').should('have.attr', 'href', teamMessages[key as TeamMemberKey].github_url).and('have.attr', 'target', '_blank')
        if (teamMessages[key as TeamMemberKey].linkedin_url.length > 1)
          cy.get('[data-test="member-page-linkedin"]').should('have.attr', 'href', teamMessages[key as TeamMemberKey].linkedin_url).and('have.attr', 'target', '_blank')
        if (teamMessages[key as TeamMemberKey].twitter_url.length > 1)
          cy.get('[data-test="member-page-twitter"]').should('have.attr', 'href', teamMessages[key as TeamMemberKey].twitter_url).and('have.attr', 'target', '_blank')
        if (teamMessages[key as TeamMemberKey].website.length > 1)
          cy.get('[data-test="member-page-website"]').should('have.attr', 'href', teamMessages[key as TeamMemberKey].website).and('have.attr', 'target', '_blank')
        if (teamMessages[key as TeamMemberKey].website.length > 1)
          cy.get('[data-test="member-page-description"]').should('contain.text', teamMessages[key as TeamMemberKey].description)
      })
    })
  })
})
