import "@/styles/globals.css";

import { type Metadata } from "next";
import { NavHeader } from "@/components/organisms/nav-header";
import { Footer } from "@/components/organisms/footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <NavHeader />
      {children}
      <Footer />
    </>
  );
}
